---
- hosts: CSR-01
  gather_facts: false
  connection: local

  tasks:
   - name: show run 
     ios_command:
       commands:
         - show version   
       host: "{{ ansible_host }}"
       username: roger
       password: password123
     register: config

   - name: save output to /etc/ansible/backups 
     copy: 
       content: "{{ config.stdout[0] }}"
       dest: "/etc/ansible/backups/show_run_{{ inventory_hostname }}.txt"

 

