---
- hosts: ios
  gather_facts: false
  connection: local

  vars: 
    my_list: []

  tasks: 
  - name: show interfaces 
    ios_facts: 
      gather_subset: "interfaces"
      provider: "{{ cli }}"

  - name: get interface
    set_fact: 
      my_list: '{{my_list + [item]}}'
    with_items: "{{ ansible_net_interfaces }}"

  - debug:
      var: my_list

  - name: loop through 
    with_items: " {{ my_list }}"
    ios_command:
      commands: show interface {{ item }} switchport | inc Operational Mode 
      provider: "{{ cli }}"
    register: output

  - name: show output
    with_indexed_items: "{{ my_list[0:2] }}"
    debug: var=output.results[{{ item.0 }}].stdout


  - block: 
    - name: write config to interface 
      with_indexed_items: " {{ my_list }} "
      ios_config:
        lines: description STATUS is UP - "config by Ansible"
        replace: line 
        parents: interface {{ item.1 }}
        provider: "{{ cli }}" 
        match: none
      when: "'Operational Mode: static access' in output.results[{{ item.0 }}].stdout"

 
